kind: pipeline
name: TWRP for Deen

clone:
  depth: 1

steps:
- name: building
  image: fr3akyphantom/droid-builder:latest
  commands:
  - bash twrp-build.sh
- name: publish
  image: plugins/github-release
  settings:
    api_key:
	from_secret: github_token
    files:
      - final/*.img
      - final/*.zip
   checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
  when:
    event: tag